### ISSUE TITLE
compatibilité Elastic 7.6.1 (oss)

### ISSUE THREAD

**Issue by leadwire-apm** [leadwire-apm/reports#3]

**Comment by WassimDhib** [comment]
- Create watcher OK
- List Watcher OK
- Execute Watcher KO


```
{"type":"response","@timestamp":"2020-05-16T08:20:16Z","tags":[],"pid":502,"method":"post","statusCode":200,"req":{"url":"/api/sentinl/watcher/a9cea6b0-974d-11ea-89a6-43a3db74a6e3","method":"post","headers":{"x-proxy-user":"admin","x-proxy-roles":"admin","x-forwarded-for":"88.142.195.219","host":"kibana:8008","connection":"close","content-length":"0","accept":"application/json, text/plain, */*","kbn-version":"7.6.1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","origin":"https://kibana.leadwire.io","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://kibana.leadwire.io/app/sentinl","accept-encoding":"gzip, deflate, br","accept-language":"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"staging-watcher-website"},"remoteAddress":"192.168.0.7","userAgent":"192.168.0.7","referer":"https://kibana.leadwire.io/app/sentinl"},"res":{"statusCode":200,"responseTime":9,"contentLength":9},"message":"POST /api/sentinl/watcher/a9cea6b0-974d-11ea-89a6-43a3db74a6e3 200 9ms - 9.0B"}
{"type":"error","@timestamp":"2020-05-16T08:20:16Z","tags":[],"pid":502,"level":"error","error":{"message":"execute advanced watcher : get elasticsearch payload : search : this._client[method] is not a function","name":"Error","stack":"Error: execute advanced watcher : get elasticsearch payload : search : this._client[method] is not a function\n    at handleESError (/usr/share/kibana/plugins/sentinl/server/lib/handle_es_error.js:29:17)\n    at handler (/usr/share/kibana/plugins/sentinl/server/routes/watcher.js:164:16)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/sentinl/watcher/_execute","path":"/api/sentinl/watcher/_execute","href":"/api/sentin /watcher/_execute"},"message":"execute advanced watcher : get elasticsearch payload : search : this._client[method] is not a function"}
{"type":"response","@timestamp":"2020-05-16T08:20:16Z","tags":[],"pid":502,"method":"post","statusCode":500,"req":{"url":"/api/sentinl/watcher/_execute","method":"post","headers":{"x-proxy-user":"admin","x-proxy-roles":"admin","x-forwarded-for":"88.142.195.219","host":"kibana:8008","connection":"close","content-length":"783","accept":"application/json, text/plain, */*","kbn-version":"7.6.1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36","content-type":"application/json;charset=UTF-8","origin":"https://kibana.leadwire.io","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://kibana.leadwire.io/app/sentinl","accept-encoding":"gzip, deflate, br","accept-language":"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"staging-watcher-website"},"remoteAddress":"192.168.0.7","userAgent":"192.168.0.7","referer":"https://kibana.leadwire.io/app/sentinl"},"res":{"statusCode":500,"responseTime":8,"contentLength":9},"message":"POST /api/sentinl/watcher/_execute 500 8ms - 9.0B"}
{"type":"error","@timestamp":"2020-05-16T08:20:16Z","tags":["warning","process"],"pid":502,"level":"error","error":{"message":"TypeError: this._internal_client[method] is not a function\n    at EsApi.create (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:243:22)\n    at EsApi.logAlarm (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:111:31)\n    at WatcherHandler.execute (/usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:278:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: TypeError: this._internal_client[method] is not a function\n    at EsApi.create (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:243:22)\n    at EsApi.logAlarm (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:111:31)\n    at WatcherHandler.execute (/usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:278:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at emitWarning (internal/process/promises.js:97:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"TypeError: this._internal_client[method] is not a function\n    at EsApi.create (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:243:22)\n    at EsApi.logAlarm (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:111:31)\n    at WatcherHandler.execute (/usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:278:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"type":"error","@timestamp":"2020-05-16T08:20:16Z","tags":["warning","process"],"pid":502,"level":"error","error":{"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)","name":"UnhandledPromiseRejectionWarning","stack":"TypeError: this._internal_client[method] is not a function\n    at EsApi.create (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:243:22)\n    at EsApi.logAlarm (/usr/share/kibana/plugins/sentinl/server/lib/api_client/es_client.js:111:31)\n    at WatcherHandler.execute (/usr/share/kibana/plugins/sentinl/server/lib/watcher_handler.js:278:22)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)"}
```
