### ISSUE TITLE
le mode pdf ne fonctionne pas 

### ISSUE THREAD

**Issue by leadwire-apm** [leadwire-apm/reports#5]
```
        "snapshot": {
          "type": "pdf",
          "url": "https://www.google.fr",
          "pdf": {
            "width": "1200",
            "height": "900"
          }
```

**Comment by leadwire-apm** [comment]
```
{"type":"log","@timestamp":"2020-04-17T14:06:54Z","tags":["error","Sentinl","report"],"pid":20750,"message":"collapse navbar: waiting for selector \"div.global-nav-link--close.global-nav-link.global-nav-link > a\" failed: timeout 5000ms exceeded"}
{"type":"log","@timestamp":"2020-04-17T14:06:54Z","tags":["error","Sentinl"],"pid":20750,"message":"staging-watcher-website-dailyreportpdf: report action : execute : puppeteer work : Protocol error (IO.read): Invalid parameters handle: string value expected: Error: Protocol error (IO.read): Invalid parameters handle: string value expected\n    at Promise (/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/lib/Connection.js:183:56)\n    at new Promise (<anonymous>)\n    at CDPSession.send (/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/lib/Connection.js:182:12)\n    at Function.readProtocolStream (/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/lib/helper.js:241:37)\n  -- ASYNC --\n    at Page.<anonymous> (/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/lib/helper.js:111:15)\n    at pdf (/usr/share/kibana/plugins/sentinl/server/lib/actions/report/puppeteer.js:122:18)"}

```
